version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: sass-loader
    versions:
    - 11.0.1
